import 'server-only';

import fs from 'node:fs/promises';
import path from 'node:path';

import {assertArchiveReady} from './drive';
import {lotFolderName} from './pipeline';
import {supabase} from './supabase';
import {
  CHANNEL_LABELS,
  STATUS_LABELS,
  type Item,
  type ItemFacts,
  type ItemImage,
} from './types';

/**
 * `item.md` is an EXPORT, not a source of truth.
 *
 * It exists so that in ten years the archive folder is readable without this
 * app, a database, or a working internet connection. It is regenerated from the
 * database on demand and the app never parses one back in — the moment a price
 * can be edited in two places, they diverge and neither is trustworthy.
 *
 * Every file this module writes says so at the top.
 */

const HEADER = [
  '<!--',
  '  Generated by the Weldam House inventory tool. Do not edit.',
  '  This file is an export of the database record, written for future readers.',
  '  Editing it changes nothing: the app never reads item.md back in, and the',
  '  next "Regenerate sidecars" will overwrite whatever you typed here.',
  '-->',
].join('\n');

export function renderSidecar(item: Item, images: ItemImage[]): string {
  const facts = (item.facts ?? {}) as ItemFacts;
  const lot = lotFolderName(item.lot_number);

  const rows: Array<[string, string | null | undefined]> = [
    ['Lot', lot],
    ['Title (NL)', item.title_nl],
    ['Title (EN)', item.title_en],
    ['Category', item.category ?? facts.category],
    ['Material', item.material ?? facts.material],
    ['Era', item.era ?? facts.era],
    ['Colour', item.colour ?? facts.colour],
    ['Dimensions (cm)', item.dimensions_cm ?? facts.dimensions_cm],
    ['Maker', item.maker ?? facts.maker],
    ['Marks found', item.marks_found ?? facts.marks_found],
    ['Marks to check', item.marks_to_check ?? facts.marks_to_check],
    ['Condition', item.condition ?? facts.condition],
    ['Confidence', item.confidence],
    ['Channel', item.channel ? CHANNEL_LABELS[item.channel] : null],
    ['Lot group', item.lot_group],
    ['Status', STATUS_LABELS[item.status]],
    ['Price (local)', formatEuro(item.price_local)],
    ['Price (intl)', formatEuro(item.price_intl)],
    ['Sold for', formatEuro(item.sold_price)],
    ['Sold at', item.sold_at],
    ['Created', item.created_at],
    ['Updated', item.updated_at],
  ];

  const lines: string[] = [
    HEADER,
    '',
    `# Lot ${lot} — ${item.title_nl ?? item.title_en ?? 'Untitled'}`,
    '',
    '| Field | Value |',
    '| --- | --- |',
  ];

  for (const [label, value] of rows) {
    lines.push(`| ${label} | ${escapeCell(value)} |`);
  }

  if (facts.reasoning) {
    lines.push('', '## Appraiser note', '', facts.reasoning);
  }

  if (item.notes) {
    lines.push('', '## Notes', '', item.notes);
  }

  lines.push('', '## Files', '');
  if (images.length === 0) {
    lines.push('_No images recorded._');
  } else {
    lines.push('| File | Original name | SHA-256 | Bytes | Web copy |');
    lines.push('| --- | --- | --- | --- | --- |');
    for (const image of images) {
      lines.push(
        `| ${escapeCell(image.archive_path ? path.posix.basename(image.archive_path) : '—')}` +
          ` | ${escapeCell(image.original_name)}` +
          ` | \`${image.sha256 ?? '—'}\`` +
          ` | ${image.bytes ?? '—'}` +
          ` | ${escapeCell(image.storage_path)}${image.is_primary ? ' (primary)' : ''} |`,
      );
    }
  }

  lines.push(
    '',
    '---',
    '',
    `_Exported ${new Date().toISOString()}. The full-resolution originals sit beside this file; the web copies live in Supabase storage._`,
    '',
  );

  return lines.join('\n');
}

function formatEuro(value: number | null | undefined): string | null {
  if (value == null) return null;
  return `€ ${Number(value).toFixed(2)}`;
}

function escapeCell(value: string | null | undefined): string {
  if (value == null || value === '') return '—';
  return String(value).replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

export interface SidecarReport {
  written: number;
  skipped: Array<{lot: number; reason: string}>;
}

/**
 * Rewrites every sidecar from the database. Writes only into
 * archive/{lot}/item.md, and only for lots whose folder already exists —
 * a sidecar is a companion to originals, not a reason to create a folder.
 */
export async function regenerateSidecars(
  onlyItemId?: string,
): Promise<SidecarReport> {
  const {archiveRoot} = await assertArchiveReady();
  const db = supabase();

  let itemsQuery = db.from('items').select('*').order('lot_number');
  if (onlyItemId) itemsQuery = itemsQuery.eq('id', onlyItemId);

  const {data: items, error} = await itemsQuery;
  if (error) throw new Error(`Could not read items: ${error.message}`);

  const report: SidecarReport = {written: 0, skipped: []};
  if (!items || items.length === 0) return report;

  const ids = items.map((row) => row.id as string);
  const {data: allImages} = await db
    .from('item_images')
    .select('*')
    .in('item_id', ids)
    .order('sort_order');

  const byItem = new Map<string, ItemImage[]>();
  for (const image of (allImages ?? []) as ItemImage[]) {
    const list = byItem.get(image.item_id) ?? [];
    list.push(image);
    byItem.set(image.item_id, list);
  }

  for (const row of items as Item[]) {
    const lot = lotFolderName(row.lot_number);
    const folder = path.join(archiveRoot, 'archive', lot);
    try {
      await fs.access(folder);
    } catch {
      report.skipped.push({
        lot: row.lot_number,
        reason: 'no archive folder on the drive',
      });
      continue;
    }

    const markdown = renderSidecar(row, byItem.get(row.id) ?? []);
    await fs.writeFile(path.join(folder, 'item.md'), markdown, 'utf8');
    report.written += 1;
  }

  return report;
}
