/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\theme\weldam.ts
 * Command: astryx theme build src\theme\weldam.ts --out src\theme\built\weldam.css
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

/**
 * weldam theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { weldamTheme } from './weldam';
 *   import './weldam.css';
 */
export const weldamTheme = {
  name: 'weldam',
  __built: true,
  tokens: {
    "--font-size-4xs": "0.375rem",
    "--font-size-3xs": "0.4375rem",
    "--font-size-2xs": "0.5625rem",
    "--font-size-xs": "0.625rem",
    "--font-size-sm": "0.8125rem",
    "--font-size-base": "0.9375rem",
    "--font-size-lg": "1.125rem",
    "--font-size-xl": "1.375rem",
    "--font-size-2xl": "1.625rem",
    "--font-size-3xl": "1.9375rem",
    "--font-size-4xl": "2.3125rem",
    "--font-size-5xl": "2.8125rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-normal)",
    "--text-heading-1-leading": "1.3846",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-normal)",
    "--text-heading-2-leading": "1.4545",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-normal)",
    "--text-heading-3-leading": "1.5556",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-normal)",
    "--text-heading-4-leading": "1.6",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-normal)",
    "--text-heading-5-leading": "1.5385",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-normal)",
    "--text-heading-6-leading": "1.6",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.6",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.5556",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.6",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.6",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.5385",
    "--text-display-1-size": "var(--font-size-5xl)",
    "--text-display-1-weight": "var(--font-weight-normal)",
    "--text-display-1-leading": "1.2444",
    "--text-display-2-size": "var(--font-size-4xl)",
    "--text-display-2-weight": "var(--font-weight-normal)",
    "--text-display-2-leading": "1.2973",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "var(--font-weight-normal)",
    "--text-display-3-leading": "1.4194",
    "--duration-fast-min": "115ms",
    "--duration-fast": "150ms",
    "--duration-fast-max": "200ms",
    "--duration-medium-min": "240ms",
    "--duration-medium": "320ms",
    "--duration-medium-max": "425ms",
    "--duration-slow-min": "600ms",
    "--duration-slow": "800ms",
    "--duration-slow-max": "1065ms",
    "--font-family-body": "var(--font-archivo), \"Segoe UI\", system-ui, -apple-system, sans-serif",
    "--font-family-heading": "var(--font-instrument-serif), Georgia, \"Times New Roman\", serif",
    "--font-family-code": "ui-monospace, \"Cascadia Mono\", \"SF Mono\", Consolas, monospace",
    "--color-syntax-keyword": "light-dark(#700084, #efa8ff)",
    "--color-syntax-string": "light-dark(#005600, #a6d2a2)",
    "--color-syntax-comment": "light-dark(#737373, #a3a3a3)",
    "--color-syntax-number": "light-dark(#6e3500, #ffb37f)",
    "--color-syntax-function": "light-dark(#00458c, #a0caff)",
    "--color-syntax-type": "light-dark(#700084, #efa8ff)",
    "--color-syntax-variable": "light-dark(#171717, #e5e5e5)",
    "--color-syntax-operator": "light-dark(#737373, #a3a3a3)",
    "--color-syntax-constant": "light-dark(#6e3500, #ffb37f)",
    "--color-syntax-tag": "light-dark(#89001a, #ffaeaa)",
    "--color-syntax-attribute": "light-dark(#584400, #eec12f)",
    "--color-syntax-property": "light-dark(#005348, #83dac9)",
    "--color-syntax-punctuation": "light-dark(#6e6e6e, #a0a0a0)",
    "--color-syntax-background": "light-dark(#fafafa, #0a0a0a)",
    "--color-background-surface": "light-dark(#FFFFFF, #26221C)",
    "--color-background-body": "light-dark(#F7F1E4, #1A1713)",
    "--color-background-card": "light-dark(#FFFFFF, #26221C)",
    "--color-background-popover": "light-dark(#FFFFFF, #302B23)",
    "--color-background-muted": "light-dark(#5C544A0F, #F7F1E40A)",
    "--color-accent": "light-dark(#A63A1C, #E8B84B)",
    "--color-accent-muted": "light-dark(#A63A1C1F, #E8B84B29)",
    "--color-neutral": "light-dark(#2419151A, #EAE1D533)",
    "--color-overlay": "light-dark(#211D1899, #0F0D0ABF)",
    "--color-overlay-hover": "light-dark(#5C544A0F, #F7F1E40F)",
    "--color-overlay-pressed": "light-dark(#5C544A1C, #F7F1E41C)",
    "--color-text-primary": "light-dark(#211D18, #F0E9DA)",
    "--color-text-secondary": "light-dark(#5C544A, #B5AB9A)",
    "--color-text-disabled": "light-dark(#9A9184, #7E766A)",
    "--color-text-accent": "light-dark(#A63A1C, #E8B84B)",
    "--color-on-dark": "#ffffff",
    "--color-on-light": "#171717",
    "--color-on-accent": "light-dark(#FFFFFF, #211D18)",
    "--color-on-success": "light-dark(#FFFFFF, #211D18)",
    "--color-on-error": "light-dark(#FFFFFF, #211D18)",
    "--color-on-warning": "light-dark(#FFFFFF, #211D18)",
    "--color-icon-accent": "light-dark(#A63A1C, #E8B84B)",
    "--color-icon-primary": "light-dark(#211D18, #F0E9DA)",
    "--color-icon-secondary": "light-dark(#5C544A, #B5AB9A)",
    "--color-icon-disabled": "light-dark(#9A9184, #7E766A)",
    "--color-success": "light-dark(#3E6B45, #7FA886)",
    "--color-error": "light-dark(#9C3719, #D4674A)",
    "--color-warning": "light-dark(#8A5A14, #D9A441)",
    "--color-success-muted": "light-dark(#3E6B4524, #7FA88629)",
    "--color-error-muted": "light-dark(#9C371924, #D4674A29)",
    "--color-warning-muted": "light-dark(#8A5A1424, #D9A44129)",
    "--color-border": "light-dark(#D9CDB4, #3C352C)",
    "--color-border-emphasized": "light-dark(#C3B393, #584F42)",
    "--color-skeleton": "light-dark(#E8DFCB, #332E26)",
    "--color-shadow": "light-dark(rgba(33, 29, 24, 0.14), rgba(0, 0, 0, 0.5))",
    "--color-tint-hover": "light-dark(#211D18, #F7F1E4)",
    "--color-background-red": "light-dark(#9C37191F, #9C371938)",
    "--color-border-red": "light-dark(#9C3719, #C4664C)",
    "--color-icon-red": "light-dark(#9C3719, #D4674A)",
    "--color-text-red": "light-dark(#6B2411, #F0B7A5)",
    "--color-background-orange": "light-dark(#C4642A24, #C4642A38)",
    "--color-border-orange": "light-dark(#B4551F, #C57A4A)",
    "--color-icon-orange": "light-dark(#B4551F, #DE9163)",
    "--color-text-orange": "light-dark(#6B3211, #F0C3A5)",
    "--color-background-yellow": "light-dark(#E8B84B3D, #E8B84B29)",
    "--color-border-yellow": "light-dark(#B8862A, #C9A24A)",
    "--color-icon-yellow": "light-dark(#8A5A14, #E8B84B)",
    "--color-text-yellow": "light-dark(#5A3B0D, #F2DCA6)",
    "--color-background-green": "light-dark(#3E6B451F, #3E6B4538)",
    "--color-border-green": "light-dark(#3E6B45, #6E9B76)",
    "--color-icon-green": "light-dark(#3E6B45, #7FA886)",
    "--color-text-green": "light-dark(#2B4B31, #B9D8BE)",
    "--color-background-teal": "light-dark(#3F5D631F, #3F5D6338)",
    "--color-border-teal": "light-dark(#3F5D63, #6B8E95)",
    "--color-icon-teal": "light-dark(#3F5D63, #7FA5AC)",
    "--color-text-teal": "light-dark(#26383C, #B3D0D5)",
    "--color-background-cyan": "light-dark(#3F5D631F, #3F5D6338)",
    "--color-border-cyan": "light-dark(#3F5D63, #6B8E95)",
    "--color-icon-cyan": "light-dark(#3F5D63, #7FA5AC)",
    "--color-text-cyan": "light-dark(#26383C, #B3D0D5)",
    "--color-background-blue": "light-dark(#3F5D631F, #3F5D6338)",
    "--color-border-blue": "light-dark(#3F5D63, #6B8E95)",
    "--color-icon-blue": "light-dark(#3F5D63, #7FA5AC)",
    "--color-text-blue": "light-dark(#26383C, #B3D0D5)",
    "--color-background-purple": "light-dark(#5C544A1F, #D9CDB41A)",
    "--color-border-purple": "light-dark(#8C8477, #6E6558)",
    "--color-icon-purple": "light-dark(#5C544A, #B5AB9A)",
    "--color-text-purple": "light-dark(#211D18, #F0E9DA)",
    "--color-background-pink": "light-dark(#5C544A1F, #D9CDB41A)",
    "--color-border-pink": "light-dark(#8C8477, #6E6558)",
    "--color-icon-pink": "light-dark(#5C544A, #B5AB9A)",
    "--color-text-pink": "light-dark(#211D18, #F0E9DA)",
    "--color-background-gray": "light-dark(#5C544A1F, #D9CDB41A)",
    "--color-border-gray": "light-dark(#8C8477, #6E6558)",
    "--color-icon-gray": "light-dark(#5C544A, #B5AB9A)",
    "--color-text-gray": "light-dark(#211D18, #F0E9DA)",
    "--radius-none": "0px",
    "--radius-inner": "3px",
    "--radius-element": "6px",
    "--radius-container": "9px",
    "--radius-page": "21px",
    "--radius-full": "9999px",
    "--shadow-low": "0 2px 4px light-dark(oklch(0 0 0 / 5%), oklch(0 0 0 / 25%)), 0 4px 8px light-dark(oklch(0 0 0 / 10%), oklch(0 0 0 / 40%)), inset 0 0 0 1px light-dark(transparent, oklch(1 0 0 / 8%))",
    "--shadow-med": "0 2px 4px light-dark(oklch(0 0 0 / 5%), oklch(0 0 0 / 35%)), 0 4px 12px light-dark(oklch(0 0 0 / 10%), oklch(0 0 0 / 50%)), inset 0 0 0 1px light-dark(transparent, oklch(1 0 0 / 12%))",
    "--shadow-high": "0 4px 6px light-dark(oklch(0 0 0 / 10%), oklch(0 0 0 / 50%)), 0 12px 24px light-dark(oklch(0 0 0 / 15%), oklch(0 0 0 / 70%)), inset 0 0 0 1px light-dark(transparent, oklch(1 0 0 / 15%))",
    "--shadow-inset-hover": "inset 0px 0px 0px 2px #0074e24D",
    "--shadow-inset-selected": "inset 0px 0px 0px 2px #0074e280",
    "--shadow-inset-success": "inset 0px 0px 0px 2px #1981004D",
    "--shadow-inset-warning": "inset 0px 0px 0px 2px #ffce2f4D",
    "--shadow-inset-error": "inset 0px 0px 0px 2px #e33f4a4D",
    "--color-background-inverted": "light-dark(#211D18, #F7F1E4)",
    "--color-track": "light-dark(#E8DFCB, #3A342B)",
    "--radius-chat": "21px",
    "--focus-outline-color": "var(--color-accent)",
    "--color-background-error-inverted": "light-dark(#9C3719, #D4674A)"
  },
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      },
      "base": {
        "letterSpacing": "-0.02em"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "button": {
      "variant:destructive": {
        "backgroundColor": "var(--color-error-muted)",
        "color": "var(--color-error)"
      },
      "base": {
        "borderRadius": "var(--radius-element)",
        "fontWeight": "var(--font-weight-semibold)",
        "letterSpacing": "0.01em"
      }
    },
    "badge": {
      "variant:info": {
        "backgroundColor": "light-dark(#0074e2, #6d9cfe)",
        "color": "light-dark(#ffffff, #171717)"
      },
      "variant:neutral": {
        "backgroundColor": "var(--color-background-gray)",
        "color": "var(--color-text-gray)"
      },
      "variant:success": {
        "backgroundColor": "light-dark(#198100, #64af4c)",
        "color": "light-dark(#ffffff, #171717)"
      },
      "variant:warning": {
        "backgroundColor": "#ffce2f",
        "color": "#171717"
      },
      "variant:error": {
        "backgroundColor": "light-dark(#c9303a, #ff705d)",
        "color": "light-dark(#ffffff, #171717)"
      },
      "variant:red": {
        "backgroundColor": "var(--color-background-red)",
        "color": "var(--color-text-red)"
      },
      "variant:orange": {
        "backgroundColor": "var(--color-background-orange)",
        "color": "var(--color-text-orange)"
      },
      "variant:yellow": {
        "backgroundColor": "var(--color-background-yellow)",
        "color": "var(--color-text-yellow)"
      },
      "variant:green": {
        "backgroundColor": "var(--color-background-green)",
        "color": "var(--color-text-green)"
      },
      "variant:teal": {
        "backgroundColor": "var(--color-background-teal)",
        "color": "var(--color-text-teal)"
      },
      "variant:cyan": {
        "backgroundColor": "var(--color-background-cyan)",
        "color": "var(--color-text-cyan)"
      },
      "variant:blue": {
        "backgroundColor": "var(--color-background-blue)",
        "color": "var(--color-text-blue)"
      },
      "variant:purple": {
        "backgroundColor": "var(--color-background-purple)",
        "color": "var(--color-text-purple)"
      },
      "variant:pink": {
        "backgroundColor": "var(--color-background-pink)",
        "color": "var(--color-text-pink)"
      },
      "variant:gray": {
        "backgroundColor": "var(--color-background-gray)",
        "color": "var(--color-text-gray)"
      },
      "variant:tag": {
        "backgroundColor": "var(--color-accent)",
        "color": "var(--color-on-accent)",
        "fontFamily": "var(--font-family-body)",
        "fontWeight": "var(--font-weight-semibold)",
        "fontVariantNumeric": "tabular-nums",
        "padding": "0.3em 0.7em 0.3em 0.95em",
        "borderRadius": "0",
        "clipPath": "polygon(0 50%, 12% 0, 100% 0, 100% 100%, 12% 100%)",
        "transform": "rotate(-4deg)",
        "whiteSpace": "nowrap"
      },
      "variant:tag-logo": {
        "backgroundColor": "var(--color-accent)",
        "color": "var(--color-on-accent)",
        "fontFamily": "var(--font-family-heading)",
        "fontWeight": "var(--font-weight-normal)",
        "fontSize": "var(--font-size-lg)",
        "lineHeight": "1",
        "padding": "0.18em 0.42em 0.18em 0.5em",
        "borderRadius": "0",
        "clipPath": "polygon(0 50%, 16% 0, 100% 0, 100% 100%, 16% 100%)",
        "transform": "rotate(-8deg)",
        "WebkitMask": "radial-gradient(circle 0.1em at 0.3em 50%, transparent 97%, #000 100%)",
        "mask": "radial-gradient(circle 0.1em at 0.3em 50%, transparent 97%, #000 100%)",
        "whiteSpace": "nowrap"
      },
      "variant:tag-sold": {
        "backgroundColor": "var(--color-text-secondary)",
        "color": "var(--color-background-body)",
        "fontFamily": "var(--font-family-body)",
        "fontWeight": "var(--font-weight-semibold)",
        "fontVariantNumeric": "tabular-nums",
        "padding": "0.3em 0.7em 0.3em 0.95em",
        "borderRadius": "0",
        "clipPath": "polygon(0 50%, 12% 0, 100% 0, 100% 100%, 12% 100%)",
        "transform": "rotate(-4deg)",
        "whiteSpace": "nowrap"
      }
    },
    "statusdot": {
      "variant:success": {
        "backgroundColor": "light-dark(#198100, #64af4c)"
      },
      "variant:warning": {
        "backgroundColor": "#ffce2f"
      },
      "variant:error": {
        "backgroundColor": "light-dark(#c9303a, #ff705d)"
      },
      "variant:accent": {
        "backgroundColor": "light-dark(#0074e2, #6d9cfe)"
      }
    },
    "banner": {
      "status:info": {
        "--color-accent-muted": "var(--color-background-blue)",
        "--color-text-primary": "var(--color-text-blue)",
        "--color-text-secondary": "var(--color-text-blue)",
        "--color-accent": "var(--color-text-blue)"
      },
      "status:success": {
        "--color-text-primary": "var(--color-text-green)",
        "--color-text-secondary": "var(--color-text-green)",
        "--color-success": "var(--color-text-green)"
      },
      "status:warning": {
        "--color-text-primary": "var(--color-text-yellow)",
        "--color-text-secondary": "var(--color-text-yellow)",
        "--color-warning": "var(--color-text-yellow)"
      },
      "status:error": {
        "--color-text-primary": "var(--color-text-red)",
        "--color-text-secondary": "var(--color-text-red)",
        "--color-error": "var(--color-text-red)"
      },
      "base": {
        "borderRadius": "var(--radius-element)"
      }
    },
    "switch": {
      "base": {
        "--color-background-gray": "var(--color-border-emphasized)"
      }
    },
    "progressbar": {
      "base": {
        "--color-background-muted": "var(--color-border-emphasized)"
      },
      "variant:accent": {
        "--color-accent": "#0074e2"
      },
      "variant:success": {
        "--color-success": "#198100"
      },
      "variant:warning": {
        "--color-warning": "#ffce2f"
      },
      "variant:error": {
        "--color-error": "#c9303a"
      }
    },
    "card": {
      "base": {
        "padding": "var(--spacing-3)"
      }
    },
    "section": {
      "base": {
        "padding": "var(--spacing-3)"
      }
    },
    "table-header-cell": {
      "base": {
        "backgroundColor": "var(--color-background-body)",
        "fontWeight": "var(--font-weight-semibold)",
        "letterSpacing": "0.02em",
        "textTransform": "uppercase",
        "fontSize": "var(--font-size-2xs)",
        "color": "var(--color-text-secondary)"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },

};
