/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\theme\weldam.ts
 * Command: astryx theme build src\theme\weldam.ts --out src\theme\built\weldam.css
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
    'tag': true;
    'tag-logo': true;
    'tag-sold': true;
  }
}
